[나봄 조][나봄]1장 1주차 PR 제출합니다.
woowacourse-tobi-spring-study/tobi-vol1 pull request #20
Opened 2021-05-02 16:17 UTC by YounghoonKwon

나봄 찐팬 1호

2021-05-02 18:09 UTC, bperhaps commented on README.md
> +둘의 차이: https://hojak99.tistory.com/347
둘이 차이에 대해 좀 더 설명해주세요. 저는 이해가 잘 안가네요

2021-05-02 18:09 UTC, bperhaps commented on README.md
> +- 추상 클래스를 사용시, 내부 코드에서 connection을 재정의 해줘야 하지만, 인터페이스를 사용시, 외부에서 갈아끼워주기만 하면 된다.
결합도와 응집도에 대한 내용이 완전 빠졌는데 이유가 있나요?

2021-05-02 18:09 UTC, bperhaps commented on README.md
> +#### 스프링의 IoC(제어의 역전)
여긴 이번주 범위가 아니라 나중에 하겠습니다.

2021-05-03 13:48 UTC, thisisyoungbin commented
라이언 안녕하세요~~

꼼꼼한 정리와 직접 만든 예시까지.. 만약 나중에 개념정리를 다시 하게 되는 경우가 생길 때 봐도 좋을 거 같네요!
IoC까지 벌써 끝내신 거 같은데 IoC 부분은 이번주에 저도 공부하고 정리하고 또 코멘트 남길게요~

정리하시느라 고생많으셨어요!! 스터디 끝까지 같이 화이팅!!

2021-05-03 14:33 UTC, wannte requested changes
글 디게 열심히 잘 작성해주셨네요.. 완무룩..

2021-05-03 14:33 UTC, wannte commented on README.md
> +}
```suggestion
interface CarFactory {
    public Car getCar();
}

class MustangFactory implements CarFactory {
  @Override
  public Car getCar() {
    return new Mustang();
  }
}
  
class BenzFactory implements CarFactory {
  @Override
  public Car getCar() {
    return new Benz();
  }
}
```

제가 이해라기로는 팩토리 메소드 패턴은 상속구조를 이용해서 어떠한 오브젝트를 생성할지 결정해주는? 방법으로 이해했는데요!

라이언은 어떻게 생각하시나요!?

2021-05-03 14:33 UTC, wannte commented on README.md
> +#### 스프링의 IoC(제어의 역전)
222222222

2021-05-04 02:11 UTC, YounghoonKwon commented on README.md
> +}
수정! 제가 얕게 이해했네용
수정한 코드에서 abstractFactory 가 부모 역할을 하고,
실제 팩토리에서는 어떤 타입의 팩토리를 사용할지 인자로 받게끔 수정했어요.
이렇게 하면 상속구조를 이용해서 어떠한 오브젝트를 생성할지 팩토리에서 결정하게 되는데
이것을 팩토리 패턴이라고 하는것으로 이해했어요

2021-05-04 02:12 UTC, YounghoonKwon commented on README.md
> +- 추상 클래스를 사용시, 내부 코드에서 connection을 재정의 해줘야 하지만, 인터페이스를 사용시, 외부에서 갈아끼워주기만 하면 된다.
수정했습니당

2021-05-04 02:12 UTC, YounghoonKwon commented on README.md
> +둘의 차이: https://hojak99.tistory.com/347
내용 보충 했슴니당

2021-05-04 09:51 UTC, wannte approved these changes
확인했습니다 굳굳!

2021-05-04 14:07 UTC, bperhaps approved these changes

2021-05-04 14:56 UTC, qhals321 approved these changes
정리가 정말 어마어마하네유!!!!!
훌륭 그 자체!!!

2021-05-05 13:00 UTC, merged